# Generated by Django 5.0 on 2023-12-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Оставленный отзыв', 'verbose_name_plural': 'Оставленные отзывы'},
        ),
    ]
